### ISSUE TITLE
``$index`` is deprecated in Vue 2.0

### ISSUE THREAD

**Issue by RexZhang4321** [jkgeekJack/VueExample#1]
At line 64 
`<td class="text-center"><button @click="deletePerson($index)">Delete</button></td>`,
there is a variable ``$index``, which has been deprecated in Vue 2.0. See [https://github.com/vuejs/vue/issues/2873](url) for more details. Using the this old version will cause an error in my browser.

Anyway, thank you for this simple example! I really appreciate it!

**Comment by jkgeekJack** [comment]
I have found this error while I was writing code.Thank you for pointing out for others.I still recommend you and other to use the latest version of Vue
